networks:
  databases:
    external: true
    name: databases
  monitoring:
    external: true
    name: monitoring
    
services:
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - databases

  redis_exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis_exporter
    restart: unless-stopped
    ports:
      - "9121:9121"
    environment:
      - REDIS_ADDR=redis://redis:6379
      - REDIS_PASSWORD=yourpassredis
    networks:
      - databases
      - monitoring
    labels:
      - "traefik.enable=true"
    
volumes:
  redis_data:
    driver: local
    name: redis_data

